### ISSUE TITLE
plotly.js test mocks 

### ISSUE THREAD

**Issue by chriddyp** [mbejda/plotlychartexport#1]
Nice work!!

Not sure if you've seen these, but there is a big set of test mocks that is used in the plotly.js repo to test all of the different chart types: https://github.com/plotly/plotly.js/tree/master/test/image/mocks. You might be interested in running those mocks against the project to verify that all of the charts render appropriately.

**Comment by chriddyp** [comment]
This isn't actually an issue, so I'll close it down, I just wanted to share that resource with you :)

**Comment by mbejda** [comment]
@chriddyp good idea! I'll write some tests for it this week.
